name: LoC Limitations

on: [push, pull_request]

jobs:
  run-shell-commands: 
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "First GitHub Action"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-window-commands:
    runs-on: windows-2022
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash


